version: '3.0'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3300:3000"
    depends_on:
      - mongo
    restart: unless-stopped


  mongo:
    image: mongo:5
    ports:
      - "27018:27017"
